Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude: ["spec/**/*.rb"]

Metrics/LineLength:
  Max: 100
  Exclude: ["spec/**/*.rb"]

Lint/UnneededSplatExpansion:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
