name: Update Nix dependencies

on:
  schedule:
    - cron: "0 0 * * 3" # run weekly on Wednesdays
  workflow_dispatch:

jobs:
  update-deps-conservative:
    runs-on: ubuntu-latest
    permissions:
      # So that `create-pull-request` can... create a pull request :)
      # https://github.com/peter-evans/create-pull-request#action-inputs
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            system-features = benchmark big-parallel kvm nixos-test uid-range
      - name: update lockfiles
        run: nix run '.#devshell' -- update-deps-conservative
      - name: create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: create-pull-request/update-nix-deps
          title: "[create-pull-request] Update Nix dependencies"
          body: |
            Update Nix dependencies in `Gemfile.nix.lock` and `gemset.nix`.

            Auto-generated by [create-pull-request][1].

            [1]: https://github.com/peter-evans/create-pull-request
